apiVersion: v1
kind: ConfigMap
metadata:
  name: rings-config-mindie-server  # The value of DepolymentName must be the same as the name attribute of the following deployment. The prefix rings-config- cannot be modified.
  namespace: mindie
  labels:
    ring-controller.atlas: ascend-910b
data:
  hccl.json: |
    {
        "status":"initializing"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindie-server               # The value of this parameter must be consistent with the name of ConfigMap.
  annotations:
    sp-block: "16"
  labels:
    app: mindie-server
    ring-controller.atlas: ascend-910b
  namespace: mindie                   # Select a proper namespace based on the site requirements. (The namespaces of ConfigMap and deployments must be the same.)
spec:
  replicas: 1                        # The number of service pods launched, each pod being a complete PD-separated inference service.
  selector:
    matchLabels:
      app: mindie-server
  template:
    metadata:
      labels:
        app: mindie-server
        ring-controller.atlas: ascend-910b
        deploy-name: mindie-server  # The value must be the same as that of Deployment name.
    spec:
      schedulerName: volcano
      nodeSelector:
        accelerator: huawei-Ascend910
        accelerator-type: module-a3-16
      terminationGracePeriodSeconds: 10
      containers:
        - image: mindie:1.0.0-aarch64-800I-A2
          imagePullPolicy: IfNotPresent
          name: mindie-server
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - "$MIES_INSTALL_PATH/scripts/http_client_ctl/probe.sh readiness single_container"
            periodSeconds: 180
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - "$MIES_INSTALL_PATH/scripts/http_client_ctl/probe.sh liveness single_container"
            periodSeconds: 180
          startupProbe:
            exec:
              command:
              - bash
              - -c
              - "$MIES_INSTALL_PATH/scripts/http_client_ctl/probe.sh startup single_container"
            periodSeconds: 180
            failureThreshold: 30
          env:
          - name: MINDIE_USER_HOME_PATH
            value: /usr/local
          - name: CANN_INSTALL_PATH
            value: $(MINDIE_USER_HOME_PATH)/Ascend
          - name: MIES_INSTALL_PATH
            value: $(MINDIE_USER_HOME_PATH)/Ascend/mindie/latest/mindie-service
          - name: MINDIE_LLM_HOME_PATH
            value: $(MINDIE_USER_HOME_PATH)/Ascend/mindie/latest/mindie-llm
          - name: CONFIG_FROM_CONFIGMAP_PATH
            value: /mnt/configmap
          - name: CONFIG_FROM_CONFIG_FILE_PATH
            value: /mnt/config-files
          - name: MINDIE_MS_P_RATE
            value: "1"
          - name: MINDIE_MS_D_RATE
            value: "1"
          - name: MINDIE_MS_GEN_SERVER_PORT
            value: "true"
          - name: MINDIE_LOG_TO_FILE
            value: "1"
          - name: MINDIE_LOG_TO_STDOUT
            value: "1"
          - name: MINDIE_LOG_LEVEL
            value: "INFO"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: ["/bin/bash", "-c", "/mnt/configmap/boot.sh single_container; \n"]
          resources:
            requests:
              huawei.com/Ascend910: 16                         # Number of required NPUs. The maximum value is 16. You can add lines below to configure resources such as memory and CPU.
            limits:
              huawei.com/Ascend910: 16                         # The value must be consistent with that in requests.
          volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: model-path
            mountPath: /mnt/mindie-service/ms/model
          - name: ascend-910-config
            mountPath: /user/serverid/devindex/config
          - name: python-script-gen-config-single-container
            mountPath: /mnt/configmap/gen_config_single_container.py
            subPath: gen_config_single_container.py
          - name: boot-bash-script
            mountPath: /mnt/configmap/boot.sh
            subPath: boot.sh
          - name: config-volume
            mountPath: /mnt/config-files
          - name: python-file-utils
            mountPath: /mnt/configmap/file_utils.py
            subPath: file_utils.py
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      - name: model-path
        hostPath:
          path: /data/Qwen2.5-14B-Instruct
      - name: ascend-910-config
        configMap:
          name: rings-config-mindie-server
      - name: python-script-gen-config-single-container
        configMap:
          name: python-script-gen-config-single-container
      - name: boot-bash-script
        configMap:
          name: boot-bash-script
          defaultMode: 0750
      - name: config-volume
        configMap:
          name: config-file-path
      - name: python-file-utils
        configMap:
          name: python-file-utils
          defaultMode: 0550
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mindie-server
  name: mindie-server-infer
  namespace: mindie
spec:
  ports:
  - nodePort: 31015
    port: 1025
    protocol: TCP
    targetPort: 1025
  selector:
    app: mindie-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
